fixtures:
  repositories:
    'provision': "git://github.com/puppetlabs/provision.git"
  forge_modules:
    facts:
      repo: 'puppetlabs-facts'
      ref: '1.1.0'
    mountcore:
      repo: 'puppetlabs-mount_core'
      ref: '1.0.4'
    puppet_agent:
      repo: 'puppetlabs-puppet_agent'
      ref: '4.1.1'
    stdlib:
      repo: 'puppetlabs-stdlib'
      ref: '6.5.0'
  symlinks:
    'lvm': "#{source_dir}"
